services:
    server:
        public: true
        container_name: server
        image: fredblgr/ubuntu-novnc:20.04
        ports:
            - 6080:80
        environment:
            - GEOMETRY=1280x768
            - TZ=Asia/Shanghai
            - DEPTH=24
        volumes: 
            - /root/Desktop
            - /home
        resources:
          cpu: 2000m
          memory: 3064Mi
          storage:
            size: 2Gi
            class: standard
