services:
    server:
        public: true
        container_name: server
        image: dorowu/ubuntu-desktop-lxde-vnc
        ports:
            - 8080:80
        environment:
            - GEOMETRY=1280x768
            - TZ=Asia/Shanghai
            - DEPTH=24
        volumes: 
            - /root/Desktop
            - /home
        resources:
          cpu: 2000m
          memory: 3024Mi
          storage:
            size: 10Gi
            class: standard
